version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    #env_file:
    #  - .backend/.env

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: react-frontend
      ports:
        - "5173:5173"
      volumes:
        - ./frontend:/app  # Monta el código fuente
        - /app/node_modules  # Evita sobrescribir dependencias
      environment:
        - CHOKIDAR_USEPOLLING=true  # Para detectar cambios en Docker