version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    #env_file:
    #  - .backend/.env